openais: change SRC_URI http to fix error
Follow Up Flag:	Follow up
Flag Status:	Flagged

From: Armin Kuster <akuster@mvista.com>

ERROR: openais-1.1.4-r0 do_fetch: Error executing a python function in exec_python_func()
autogenerated:

ftp://ftp@ breaks the fetcher and really is not needed.

Signed-off-by: Armin Kuster <akuster@mvista.com>
Signed-off-by: Alexandru.Vaduva <alexandru.vaduva@linux.com>